-- Seed: 003_seed_words.sql
-- Description: 100 vocabulary words across different topics and CEFR levels
-- Created: 2024-01-01

BEGIN;

INSERT INTO words (
    word, slug, part_of_speech, cefr_level, topic, subtopic, topics, frequency,
    register, phonetic_ipa, phonetic_respelling, audio_url,
    definitions, examples, synonyms, antonyms, collocations,
    translations, memory_tip
) VALUES

-- ===== A1 LEVEL - GREETINGS & BASICS =====
('hello', 'hello', 'interjection', 'A1', 'greetings', 'basic', ARRAY['greetings','social'], 'very_common', 'neutral',
'/həˈloʊ/', 'huh-LOH', '/audio/hello.mp3',
'[{"sense":1,"definition":"Used as a greeting when meeting or acknowledging someone","usage_note":"Most common English greeting"}]',
'[{"sentence":"Hello! How are you?","translation":"مرحبا! كيف حالك؟"},{"sentence":"She said hello to her teacher.","translation":"قالت مرحبا لمعلمتها."}]',
ARRAY['hi','hey','greetings','howdy'], ARRAY['goodbye','bye'], ARRAY['say hello','hello there','hello everyone'],
'{"ar":"مرحبا","fr":"bonjour","es":"hola","de":"hallo","zh":"你好"}',
'Think of the phone - you always say hello when you answer!'),

('goodbye', 'goodbye', 'interjection', 'A1', 'greetings', 'basic', ARRAY['greetings','social'], 'very_common', 'neutral',
'/ˌɡʊdˈbaɪ/', 'good-BY', '/audio/goodbye.mp3',
'[{"sense":1,"definition":"Used when parting from someone","usage_note":"Can be shortened to ''bye''"}]',
'[{"sentence":"Goodbye! See you tomorrow!","translation":"وداعا! أراك غدا!"},{"sentence":"We said our goodbyes at the airport.","translation":"ودعنا بعضنا في المطار."}]',
ARRAY['bye','farewell','see you','later','cheerio'], ARRAY['hello','hi'], ARRAY['say goodbye','wave goodbye'],
'{"ar":"وداعا","fr":"au revoir","es":"adiós","de":"auf Wiedersehen","zh":"再见"}',
'God be with you - the original meaning of goodbye!'),

('please', 'please', 'adverb', 'A1', 'manners', 'politeness', ARRAY['manners','social','basics'], 'very_common', 'neutral',
'/pliːz/', 'PLEEZ', '/audio/please.mp3',
'[{"sense":1,"definition":"Used to make a request more polite","usage_note":"Essential for polite English"},{"sense":2,"definition":"Used to agree to a request (''Yes, please'')"}]',
'[{"sentence":"Can I have some water, please?","translation":"هل يمكنني الحصول على بعض الماء من فضلك؟"},{"sentence":"Please sit down.","translation":"من فضلك اجلس."}]',
ARRAY['kindly','if you please'], ARRAY[], ARRAY['yes please','please help','please note'],
'{"ar":"من فضلك","fr":"s''il vous plaît","es":"por favor","de":"bitte","zh":"请"}',
'Saying please shows you respect others!'),

('thank you', 'thank-you', 'interjection', 'A1', 'manners', 'politeness', ARRAY['manners','social','basics'], 'very_common', 'neutral',
'/ˈθæŋk juː/', 'THANK yoo', '/audio/thank_you.mp3',
'[{"sense":1,"definition":"An expression of gratitude"}]',
'[{"sentence":"Thank you for your help!","translation":"شكرا لك على مساعدتك!"},{"sentence":"Thank you very much, I appreciate it.","translation":"شكرا جزيلا، أنا أقدر ذلك."}]',
ARRAY['thanks','cheers','many thanks','much appreciated'], ARRAY['you''re welcome'], ARRAY['thank you very much','thank you so much'],
'{"ar":"شكرا","fr":"merci","es":"gracias","de":"danke","zh":"谢谢"}',
'Two magic words that open every heart!'),

('water', 'water', 'noun', 'A1', 'food_drink', 'beverages', ARRAY['food_drink','nature','basics'], 'very_common', 'neutral',
'/ˈwɔːtər/', 'WAW-ter', '/audio/water.mp3',
'[{"sense":1,"definition":"A clear liquid that has no color, taste, or smell and is essential for life"},{"sense":2,"definition":"A body of water such as a sea, river, or lake"}]',
'[{"sentence":"I drink eight glasses of water every day.","translation":"أشرب ثمانية أكواب من الماء كل يوم."},{"sentence":"The water in this lake is very clear.","translation":"الماء في هذه البحيرة صافٍ جداً."}]',
ARRAY['H2O','liquid'], ARRAY[], ARRAY['drink water','water bottle','water glass','hot water'],
'{"ar":"ماء","fr":"eau","es":"agua","de":"Wasser","zh":"水"}',
'Water - the source of all life!'),

-- ===== A1 - NUMBERS & TIME =====
('one', 'one', 'number', 'A1', 'numbers', 'cardinal', ARRAY['numbers','basics','math'], 'very_common', 'neutral',
'/wʌn/', 'WUN', '/audio/one.mp3',
'[{"sense":1,"definition":"The number 1"},{"sense":2,"definition":"A single person or thing"}]',
'[{"sentence":"I have one sister.","translation":"لدي أخت واحدة."},{"sentence":"One plus one equals two.","translation":"واحد زائد واحد يساوي اثنين."}]',
ARRAY['single','sole'], ARRAY['many','several'], ARRAY['one day','one more','number one'],
'{"ar":"واحد","fr":"un","es":"uno","de":"ein","zh":"一"}',
'One finger up = number 1!'),

('today', 'today', 'adverb', 'A1', 'time', 'days', ARRAY['time','basics','daily_life'], 'very_common', 'neutral',
'/təˈdeɪ/', 'tuh-DAY', '/audio/today.mp3',
'[{"sense":1,"definition":"On this present day"},{"sense":2,"definition":"The present time or age"}]',
'[{"sentence":"What are you doing today?","translation":"ماذا ستفعل اليوم؟"},{"sentence":"Today is Monday.","translation":"اليوم هو الاثنين."}]',
ARRAY['this day','nowadays'], ARRAY['yesterday','tomorrow'], ARRAY['today''s lesson','earlier today','later today'],
'{"ar":"اليوم","fr":"aujourd''hui","es":"hoy","de":"heute","zh":"今天"}',
'TO + DAY = this day!'),

-- ===== A1 - FAMILY =====
('mother', 'mother', 'noun', 'A1', 'family', 'immediate', ARRAY['family','people','basics'], 'very_common', 'neutral',
'/ˈmʌðər/', 'MUH-ther', '/audio/mother.mp3',
'[{"sense":1,"definition":"A female parent"},{"sense":2,"definition":"A woman who has given birth to a child"}]',
'[{"sentence":"My mother is a teacher.","translation":"أمي معلمة."},{"sentence":"She loves her mother very much.","translation":"هي تحب أمها كثيراً."}]',
ARRAY['mom','mum','mama','mummy'], ARRAY['father'], ARRAY['mother tongue','mother nature','working mother'],
'{"ar":"أم","fr":"mère","es":"madre","de":"Mutter","zh":"母亲"}',
'The M in mother stands for Magnificent!'),

('father', 'father', 'noun', 'A1', 'family', 'immediate', ARRAY['family','people','basics'], 'very_common', 'neutral',
'/ˈfɑːðər/', 'FAH-ther', '/audio/father.mp3',
'[{"sense":1,"definition":"A male parent"},{"sense":2,"definition":"A man who has a child"}]',
'[{"sentence":"My father works in a hospital.","translation":"أبي يعمل في مستشفى."},{"sentence":"He is a good father.","translation":"هو أب جيد."}]',
ARRAY['dad','daddy','papa'], ARRAY['mother'], ARRAY['father figure','founding father'],
'{"ar":"أب","fr":"père","es":"padre","de":"Vater","zh":"父亲"}',
'Father - the foundation of the family!'),

-- ===== A2 LEVEL - DAILY LIFE =====
('breakfast', 'breakfast', 'noun', 'A2', 'food_drink', 'meals', ARRAY['food_drink','daily_life','health'], 'very_common', 'neutral',
'/ˈbrekfəst/', 'BREK-fust', '/audio/breakfast.mp3',
'[{"sense":1,"definition":"The first meal of the day, eaten in the morning","usage_note":"''Break'' + ''fast'' - you break your overnight fasting"}]',
'[{"sentence":"I always eat breakfast at 7 AM.","translation":"أتناول دائماً الإفطار في الساعة 7 صباحاً."},{"sentence":"Breakfast is the most important meal of the day.","translation":"الإفطار هو أهم وجبة في اليوم."}]',
ARRAY['morning meal','first meal'], ARRAY['dinner','supper'], ARRAY['eat breakfast','skip breakfast','big breakfast','continental breakfast'],
'{"ar":"إفطار","fr":"petit-déjeuner","es":"desayuno","de":"Frühstück","zh":"早餐"}',
'Break + Fast = end your night fasting!'),

('beautiful', 'beautiful', 'adjective', 'A2', 'descriptions', 'appearance', ARRAY['descriptions','adjectives','arts'], 'very_common', 'neutral',
'/ˈbjuːtɪfəl/', 'BYOO-ti-ful', '/audio/beautiful.mp3',
'[{"sense":1,"definition":"Having beauty; pleasing to the senses or to the mind"},{"sense":2,"definition":"Very good; excellent"}]',
'[{"sentence":"What a beautiful sunset!","translation":"يا له من غروب جميل!"},{"sentence":"She has a beautiful voice.","translation":"لها صوت جميل."}]',
ARRAY['gorgeous','lovely','stunning','pretty','attractive'], ARRAY['ugly','hideous','plain'], ARRAY['beautiful day','beautiful music','naturally beautiful'],
'{"ar":"جميل","fr":"beau/belle","es":"hermoso/a","de":"schön","zh":"美丽的"}',
'Beauty is in the eye of the beholder!'),

('important', 'important', 'adjective', 'A2', 'concepts', 'quality', ARRAY['concepts','academic','daily_life'], 'very_common', 'neutral',
'/ɪmˈpɔːrtənt/', 'im-POR-tant', '/audio/important.mp3',
'[{"sense":1,"definition":"Of great significance or value; having a major effect"},{"sense":2,"definition":"Having power, authority, or influence"}]',
'[{"sentence":"Sleep is important for your health.","translation":"النوم مهم لصحتك."},{"sentence":"This is an important meeting.","translation":"هذا اجتماع مهم."}]',
ARRAY['significant','crucial','vital','essential','key'], ARRAY['unimportant','trivial','minor'], ARRAY['very important','most important','important role'],
'{"ar":"مهم","fr":"important","es":"importante","de":"wichtig","zh":"重要的"}',
'IM-PORT-ANT things are always front and center!'),

('understand', 'understand', 'verb', 'A2', 'learning', 'comprehension', ARRAY['learning','communication','basics'], 'very_common', 'neutral',
'/ˌʌndərˈstænd/', 'un-der-STAND', '/audio/understand.mp3',
'[{"sense":1,"definition":"To perceive the intended meaning of words, a language, or a speaker"},{"sense":2,"definition":"To know how someone feels or why they behave in a particular way"}]',
'[{"sentence":"Do you understand the question?","translation":"هل تفهم السؤال؟"},{"sentence":"I understand how you feel.","translation":"أفهم كيف تشعر."}]',
ARRAY['comprehend','grasp','get','follow','realize'], ARRAY['misunderstand','confuse'], ARRAY['fully understand','I understand','I don''t understand'],
'{"ar":"يفهم","fr":"comprendre","es":"entender","de":"verstehen","zh":"理解"}',
'Stand under someone''s words to really understand them!'),

('friend', 'friend', 'noun', 'A2', 'relationships', 'social', ARRAY['relationships','social','people'], 'very_common', 'neutral',
'/frend/', 'FREND', '/audio/friend.mp3',
'[{"sense":1,"definition":"A person with whom one has a bond of mutual affection"},{"sense":2,"definition":"A person who is not an enemy"}]',
'[{"sentence":"She is my best friend.","translation":"هي أفضل صديقاتي."},{"sentence":"We''ve been friends since childhood.","translation":"كنا أصدقاء منذ الطفولة."}]',
ARRAY['buddy','pal','companion','mate','ally'], ARRAY['enemy','foe','stranger'], ARRAY['best friend','close friend','make friends','old friend'],
'{"ar":"صديق","fr":"ami","es":"amigo","de":"Freund","zh":"朋友"}',
'A FRIEND is someone who stays to the END!'),

('work', 'work', 'verb', 'A2', 'jobs', 'employment', ARRAY['jobs','daily_life','economics'], 'very_common', 'neutral',
'/wɜːrk/', 'WURK', '/audio/work.mp3',
'[{"sense":1,"definition":"To be engaged in physical or mental activity in order to achieve a result"},{"sense":2,"definition":"To function or operate correctly"},{"sense":3,"definition":"Employment or a job"}]',
'[{"sentence":"I work in a bank.","translation":"أعمل في بنك."},{"sentence":"Does this machine work?","translation":"هل تعمل هذه الآلة؟"},{"sentence":"Hard work pays off.","translation":"العمل الجاد يؤتي ثماره."}]',
ARRAY['labor','toil','function','operate','job'], ARRAY['relax','rest','play'], ARRAY['hard work','work out','go to work','teamwork'],
'{"ar":"يعمل / عمل","fr":"travailler / travail","es":"trabajar / trabajo","de":"arbeiten / Arbeit","zh":"工作"}',
'Work = W(orth) + (you)R + K(nowledge)!'),

-- ===== B1 LEVEL =====
('achieve', 'achieve', 'verb', 'B1', 'success', 'goals', ARRAY['success','academic','motivation'], 'common', 'neutral',
'/əˈtʃiːv/', 'uh-CHEEV', '/audio/achieve.mp3',
'[{"sense":1,"definition":"To successfully bring about or reach a desired objective or result by effort"},{"sense":2,"definition":"To attain a certain level of performance or standard"}]',
'[{"sentence":"She worked hard to achieve her goals.","translation":"عملت بجد لتحقيق أهدافها."},{"sentence":"You can achieve anything you set your mind to.","translation":"يمكنك تحقيق أي شيء تضعه في ذهنك."}]',
ARRAY['accomplish','attain','reach','obtain','succeed'], ARRAY['fail','lose','miss'], ARRAY['achieve a goal','achieve success','achieve results'],
'{"ar":"يحقق","fr":"atteindre","es":"lograr","de":"erreichen","zh":"实现"}',
'A-CHIEVE - Always Choosing Higher Expectations!'),

('communicate', 'communicate', 'verb', 'B1', 'communication', 'social', ARRAY['communication','social','business'], 'common', 'neutral',
'/kəˈmjuːnɪkeɪt/', 'kuh-MYOO-ni-kayt', '/audio/communicate.mp3',
'[{"sense":1,"definition":"To share or exchange information, news, or ideas"},{"sense":2,"definition":"To convey or express clearly"}]',
'[{"sentence":"It''s important to communicate clearly with your team.","translation":"من المهم التواصل بوضوح مع فريقك."},{"sentence":"Animals communicate through sounds and gestures.","translation":"تتواصل الحيوانات من خلال الأصوات والإيماءات."}]',
ARRAY['convey','express','transmit','share','interact'], ARRAY['miscommunicate','hide'], ARRAY['communicate effectively','communicate ideas','communicate with'],
'{"ar":"يتواصل","fr":"communiquer","es":"comunicar","de":"kommunizieren","zh":"交流"}',
'COMM-UNITE-cate: communicating brings people together!'),

('environment', 'environment', 'noun', 'B1', 'environment', 'nature', ARRAY['environment','science','global_issues'], 'common', 'neutral',
'/ɪnˈvaɪrənmənt/', 'en-VY-run-ment', '/audio/environment.mp3',
'[{"sense":1,"definition":"The surroundings or conditions in which a person, animal, or plant lives"},{"sense":2,"definition":"The natural world, especially as affected by human activity"}]',
'[{"sentence":"We must protect the environment for future generations.","translation":"يجب أن نحمي البيئة للأجيال القادمة."},{"sentence":"The work environment greatly affects productivity.","translation":"بيئة العمل تؤثر بشكل كبير على الإنتاجية."}]',
ARRAY['surroundings','habitat','ecosystem','nature','ecology'], ARRAY[], ARRAY['natural environment','work environment','protect the environment'],
'{"ar":"بيئة","fr":"environnement","es":"medio ambiente","de":"Umwelt","zh":"环境"}',
'ENVIRON + MENT: everything that surround-ments you!'),

('opportunity', 'opportunity', 'noun', 'B1', 'success', 'chances', ARRAY['success','business','motivation'], 'common', 'neutral',
'/ˌɒpərˈtjuːnɪti/', 'op-er-TYOO-ni-tee', '/audio/opportunity.mp3',
'[{"sense":1,"definition":"A set of circumstances that makes it possible to do something"},{"sense":2,"definition":"A chance for employment or promotion"}]',
'[{"sentence":"This is a great opportunity to practice your English.","translation":"هذه فرصة رائعة لممارسة لغتك الإنجليزية."},{"sentence":"Don''t miss this opportunity!","translation":"لا تفوت هذه الفرصة!"}]',
ARRAY['chance','opening','occasion','prospect'], ARRAY['obstacle','threat'], ARRAY['golden opportunity','miss an opportunity','take the opportunity'],
'{"ar":"فرصة","fr":"opportunité","es":"oportunidad","de":"Gelegenheit","zh":"机会"}',
'OPPOR-TUNA-ITY: like a tuna, grab it when it jumps!'),

('technology', 'technology', 'noun', 'B1', 'technology', 'digital', ARRAY['technology','science','modern_life'], 'common', 'neutral',
'/tekˈnɒlədʒi/', 'tek-NOL-uh-jee', '/audio/technology.mp3',
'[{"sense":1,"definition":"The application of scientific knowledge for practical purposes"},{"sense":2,"definition":"Machinery and equipment developed from scientific knowledge"}]',
'[{"sentence":"Technology has changed the way we learn.","translation":"غيّرت التكنولوجيا طريقة تعلمنا."},{"sentence":"Modern technology makes life easier.","translation":"التكنولوجيا الحديثة تجعل الحياة أسهل."}]',
ARRAY['tech','innovation','machinery','digital tools'], ARRAY[], ARRAY['new technology','cutting-edge technology','information technology'],
'{"ar":"تكنولوجيا","fr":"technologie","es":"tecnología","de":"Technologie","zh":"技术"}',
'TECHNO + LOGY: the science of technique!'),

('challenge', 'challenge', 'noun', 'B1', 'life', 'obstacles', ARRAY['life','motivation','sports','business'], 'common', 'neutral',
'/ˈtʃælɪndʒ/', 'CHAL-inj', '/audio/challenge.mp3',
'[{"sense":1,"definition":"A task or situation that tests someone''s abilities"},{"sense":2,"definition":"An invitation to compete or prove something"},{"sense":3,"definition":"To dispute the truth or validity of something"}]',
'[{"sentence":"Learning English is a challenge, but it''s worth it.","translation":"تعلم الإنجليزية يمثل تحدياً، لكنه يستحق ذلك."},{"sentence":"She accepted the challenge and succeeded.","translation":"قبلت التحدي ونجحت."}]',
ARRAY['difficulty','test','obstacle','trial','hardship'], ARRAY['ease','simplicity'], ARRAY['face a challenge','take on a challenge','big challenge'],
'{"ar":"تحدي","fr":"défi","es":"desafío","de":"Herausforderung","zh":"挑战"}',
'Every CHALLENGE is a chance to CHANGE!'),

-- ===== B2 LEVEL =====
('sophisticated', 'sophisticated', 'adjective', 'B2', 'descriptions', 'quality', ARRAY['descriptions','culture','business'], 'common', 'formal',
'/səˈfɪstɪkeɪtɪd/', 'suh-FIS-ti-kay-tid', '/audio/sophisticated.mp3',
'[{"sense":1,"definition":"Having great knowledge and experience of the world or a particular area"},{"sense":2,"definition":"Highly developed and complex"}]',
'[{"sentence":"She has a sophisticated understanding of international politics.","translation":"لديها فهم متطور للسياسة الدولية."},{"sentence":"The new software has a sophisticated interface.","translation":"البرنامج الجديد يحتوي على واجهة متطورة."}]',
ARRAY['refined','cultured','advanced','complex','nuanced'], ARRAY['naive','simple','unsophisticated'], ARRAY['highly sophisticated','sophisticated system','sophisticated approach'],
'{"ar":"متطور","fr":"sophistiqué","es":"sofisticado","de":"anspruchsvoll","zh":"复杂的"}',
'Sophisticated people have seen the world through many experiences!'),

('perspective', 'perspective', 'noun', 'B2', 'thinking', 'viewpoint', ARRAY['thinking','academic','communication'], 'common', 'neutral',
'/pərˈspektɪv/', 'per-SPEK-tiv', '/audio/perspective.mp3',
'[{"sense":1,"definition":"A particular attitude toward or way of regarding something; a point of view"},{"sense":2,"definition":"The art of drawing solid objects on a flat surface so as to give the impression of depth"}]',
'[{"sentence":"Learning a new language gives you a different perspective on life.","translation":"تعلم لغة جديدة يمنحك منظوراً مختلفاً على الحياة."},{"sentence":"Try to see things from his perspective.","translation":"حاول أن ترى الأشياء من منظوره."}]',
ARRAY['viewpoint','standpoint','outlook','angle','position'], ARRAY[], ARRAY['from my perspective','different perspective','change perspective','put in perspective'],
'{"ar":"منظور","fr":"perspective","es":"perspectiva","de":"Perspektive","zh":"视角"}',
'PER-SPECTIVE: how you SPECifically VIEW something!'),

('significant', 'significant', 'adjective', 'B2', 'concepts', 'importance', ARRAY['concepts','academic','science'], 'common', 'formal',
'/sɪɡˈnɪfɪkənt/', 'sig-NIF-i-kant', '/audio/significant.mp3',
'[{"sense":1,"definition":"Sufficiently great or important to be worthy of attention; noteworthy"},{"sense":2,"definition":"Having a particular meaning; indicative of something"}]',
'[{"sentence":"This discovery is significant for medical research.","translation":"هذا الاكتشاف له أهمية بالغة للأبحاث الطبية."},{"sentence":"There has been a significant improvement in her pronunciation.","translation":"كان هناك تحسن ملحوظ في نطقها."}]',
ARRAY['important','notable','major','considerable','meaningful'], ARRAY['insignificant','minor','trivial'], ARRAY['significant change','significant role','statistically significant'],
'{"ar":"مهم / بارز","fr":"significatif","es":"significativo","de":"bedeutsam","zh":"重要的"}',
'SIGN-ificant: it SIGNS you toward importance!'),

('contemporary', 'contemporary', 'adjective', 'B2', 'time', 'modern', ARRAY['time','culture','arts'], 'common', 'formal',
'/kənˈtempəreri/', 'kun-TEM-puh-reh-ree', '/audio/contemporary.mp3',
'[{"sense":1,"definition":"Living or occurring at the same time"},{"sense":2,"definition":"Modern and relating to the present time"}]',
'[{"sentence":"She enjoys contemporary art and music.","translation":"تستمتع بالفن والموسيقى المعاصرة."},{"sentence":"Shakespeare and Galileo were contemporaries.","translation":"كان شكسبير وغاليليو معاصرَين."}]',
ARRAY['modern','current','present-day','up-to-date'], ARRAY['ancient','old','historic'], ARRAY['contemporary art','contemporary music','contemporary issues'],
'{"ar":"معاصر","fr":"contemporain","es":"contemporáneo","de":"zeitgenössisch","zh":"当代的"}',
'Con-TEMPO-rary: same TEMPO (time) together!'),

('phenomenon', 'phenomenon', 'noun', 'B2', 'science', 'concepts', ARRAY['science','academic','nature'], 'common', 'formal',
'/fɪˈnɒmɪnən/', 'fi-NOM-i-non', '/audio/phenomenon.mp3',
'[{"sense":1,"definition":"A fact or situation that is observed to exist or happen, especially one whose cause is in question"},{"sense":2,"definition":"A remarkable person or thing"}]',
'[{"sentence":"Climate change is a global phenomenon.","translation":"تغير المناخ ظاهرة عالمية."},{"sentence":"The Northern Lights are a natural phenomenon.","translation":"الأضواء الشمالية ظاهرة طبيعية."}]',
ARRAY['occurrence','event','occurrence','spectacle'], ARRAY[], ARRAY['natural phenomenon','social phenomenon','rare phenomenon'],
'{"ar":"ظاهرة","fr":"phénomène","es":"fenómeno","de":"Phänomen","zh":"现象"}',
'PHENO-MENON: PHENomenal things worth studying!'),

-- ===== C1 LEVEL =====
('ubiquitous', 'ubiquitous', 'adjective', 'C1', 'concepts', 'prevalence', ARRAY['concepts','academic','technology'], 'uncommon', 'formal',
'/juːˈbɪkwɪtəs/', 'yoo-BIK-wi-tus', '/audio/ubiquitous.mp3',
'[{"sense":1,"definition":"Present, appearing, or found everywhere","usage_note":"Often used to describe technology or cultural phenomena"}]',
'[{"sentence":"Smartphones have become ubiquitous in modern society.","translation":"أصبحت الهواتف الذكية في كل مكان في المجتمع الحديث."},{"sentence":"The ubiquitous coffee shop culture has spread worldwide.","translation":"ثقافة المقهى المنتشرة في كل مكان انتشرت في جميع أنحاء العالم."}]',
ARRAY['omnipresent','pervasive','prevalent','everywhere'], ARRAY['rare','scarce','absent'], ARRAY['ubiquitous presence','become ubiquitous','ubiquitous technology'],
'{"ar":"في كل مكان","fr":"omniprésent","es":"omnipresente","de":"allgegenwärtig","zh":"无处不在的"}',
'UBI-QUITOUS: UBIquitous is QUITe OBVIOUS everywhere!'),

('nuance', 'nuance', 'noun', 'C1', 'language', 'meaning', ARRAY['language','academic','communication'], 'uncommon', 'formal',
'/ˈnjuːɑːns/', 'NYOO-ahns', '/audio/nuance.mp3',
'[{"sense":1,"definition":"A subtle difference in or shade of meaning, expression, or sound"},{"sense":2,"definition":"A very slight difference in appearance, meaning, sound, etc."}]',
'[{"sentence":"Understanding the nuances of English idioms is important for fluency.","translation":"فهم الفروق الدقيقة للتعابير الإنجليزية مهم لطلاقة اللغة."},{"sentence":"His response showed great nuance.","translation":"أظهر رده دقة بالغة."}]',
ARRAY['subtlety','distinction','shade','gradation'], ARRAY[], ARRAY['subtle nuance','appreciate the nuance','cultural nuance'],
'{"ar":"دقة / فروق دقيقة","fr":"nuance","es":"matiz","de":"Nuance","zh":"细微差别"}',
'Nuance is the NEW-ANCE (new dance) of language!'),

('eloquent', 'eloquent', 'adjective', 'C1', 'communication', 'speaking', ARRAY['communication','language','arts'], 'uncommon', 'formal',
'/ˈeləkwənt/', 'EL-uh-kwent', '/audio/eloquent.mp3',
'[{"sense":1,"definition":"Fluent or persuasive in speaking or writing"},{"sense":2,"definition":"Clearly expressing or indicating something"}]',
'[{"sentence":"She gave an eloquent speech that moved the audience to tears.","translation":"ألقت خطاباً بليغاً أجهش الجمهور بالدموع."},{"sentence":"His silence was more eloquent than words.","translation":"كان صمته أبلغ من الكلمات."}]',
ARRAY['articulate','fluent','expressive','persuasive','silver-tongued'], ARRAY['inarticulate','tongue-tied','ineloquent'], ARRAY['eloquent speaker','eloquent speech','eloquent prose'],
'{"ar":"بليغ","fr":"éloquent","es":"elocuente","de":"beredt","zh":"雄辩的"}',
'ELO-QUENT people speak with QUALITY!'),

('pragmatic', 'pragmatic', 'adjective', 'C1', 'thinking', 'approach', ARRAY['thinking','business','psychology'], 'uncommon', 'neutral',
'/præɡˈmætɪk/', 'prag-MAT-ik', '/audio/pragmatic.mp3',
'[{"sense":1,"definition":"Dealing with things sensibly and realistically in a way that is based on practical rather than theoretical considerations"}]',
'[{"sentence":"We need to take a pragmatic approach to solving this problem.","translation":"نحتاج إلى اتخاذ نهج عملي لحل هذه المشكلة."},{"sentence":"A pragmatic leader focuses on what works.","translation":"القائد العملي يركز على ما ينجح."}]',
ARRAY['practical','realistic','sensible','down-to-earth'], ARRAY['idealistic','theoretical','impractical'], ARRAY['pragmatic approach','pragmatic solution','pragmatic thinking'],
'{"ar":"عملي / براغماتي","fr":"pragmatique","es":"pragmático","de":"pragmatisch","zh":"务实的"}',
'PRAGMA-TIC: doing what PRAGMA-tically works!'),

-- ===== BUSINESS ENGLISH =====
('revenue', 'revenue', 'noun', 'B2', 'business', 'finance', ARRAY['business','finance','economics'], 'common', 'formal',
'/ˈrevənjuː/', 'REV-uh-nyoo', '/audio/revenue.mp3',
'[{"sense":1,"definition":"The total amount of money received by a company for goods or services"},{"sense":2,"definition":"Income, especially when of an organization and of a substantial nature"}]',
'[{"sentence":"The company''s revenue increased by 20% this year.","translation":"ارتفع إيراداد الشركة بنسبة 20% هذا العام."},{"sentence":"Government revenue comes mainly from taxes.","translation":"تأتي إيرادات الحكومة بشكل رئيسي من الضرائب."}]',
ARRAY['income','earnings','profit','turnover'], ARRAY['expenditure','expense','cost'], ARRAY['annual revenue','revenue growth','revenue stream','generate revenue'],
'{"ar":"إيرادات","fr":"revenus","es":"ingresos","de":"Einnahmen","zh":"收入"}',
'REVE-NUE: where new money flows in!'),

('strategy', 'strategy', 'noun', 'B2', 'business', 'planning', ARRAY['business','planning','military','sports'], 'common', 'neutral',
'/ˈstrætɪdʒi/', 'STRAT-uh-jee', '/audio/strategy.mp3',
'[{"sense":1,"definition":"A plan of action designed to achieve a long-term or overall aim"},{"sense":2,"definition":"The art of planning and directing overall operations"}]',
'[{"sentence":"The company needs a new marketing strategy.","translation":"تحتاج الشركة إلى استراتيجية تسويقية جديدة."},{"sentence":"What''s your strategy for learning English?","translation":"ما هي استراتيجيتك لتعلم اللغة الإنجليزية؟"}]',
ARRAY['plan','approach','tactic','method'], ARRAY[], ARRAY['business strategy','marketing strategy','long-term strategy','exit strategy'],
'{"ar":"استراتيجية","fr":"stratégie","es":"estrategia","de":"Strategie","zh":"战略"}',
'STRAT-egy: STRATegically placing your energy!'),

('negotiate', 'negotiate', 'verb', 'B2', 'business', 'communication', ARRAY['business','communication','law'], 'common', 'formal',
'/nɪˈɡoʊʃieɪt/', 'ni-GOH-shee-ayt', '/audio/negotiate.mp3',
'[{"sense":1,"definition":"To try to reach an agreement or compromise by discussion"},{"sense":2,"definition":"To find a way over or through an obstacle or problem"}]',
'[{"sentence":"The union negotiated a better salary deal for the workers.","translation":"تفاوض الاتحاد على صفقة أجور أفضل للعمال."},{"sentence":"You can negotiate the price at this market.","translation":"يمكنك التفاوض على السعر في هذا السوق."}]',
ARRAY['bargain','discuss','mediate','broker','deal'], ARRAY[], ARRAY['negotiate a deal','negotiate terms','negotiate a salary','negotiate with'],
'{"ar":"يتفاوض","fr":"négocier","es":"negociar","de":"verhandeln","zh":"谈判"}',
'NEGO-tiate: NO GO without agreement!'),

-- ===== HEALTH & WELLNESS =====
('anxious', 'anxious', 'adjective', 'B1', 'emotions', 'feelings', ARRAY['emotions','health','psychology'], 'common', 'neutral',
'/ˈæŋkʃəs/', 'ANK-shus', '/audio/anxious.mp3',
'[{"sense":1,"definition":"Experiencing worry, unease, or nervousness"},{"sense":2,"definition":"Very eager or wanting something very much"}]',
'[{"sentence":"She felt anxious before the exam.","translation":"شعرت بالقلق قبل الامتحان."},{"sentence":"He was anxious to hear the results.","translation":"كان حريصاً على سماع النتائج."}]',
ARRAY['worried','nervous','uneasy','tense','apprehensive'], ARRAY['calm','relaxed','confident'], ARRAY['feel anxious','anxious about','anxious to','make someone anxious'],
'{"ar":"قلق","fr":"anxieux","es":"ansioso","de":"ängstlich","zh":"焦虑的"}',
'ANXI-OUS: ANXiety makes us feel nervous!'),

('resilient', 'resilient', 'adjective', 'B2', 'character', 'strength', ARRAY['character','psychology','health','motivation'], 'common', 'neutral',
'/rɪˈzɪliənt/', 'ri-ZIL-ee-unt', '/audio/resilient.mp3',
'[{"sense":1,"definition":"Able to withstand or recover quickly from difficult conditions"},{"sense":2,"definition":"Of a substance or object: able to recoil or spring back into shape after bending or compressing"}]',
'[{"sentence":"Children are remarkably resilient when given proper support.","translation":"الأطفال لديهم مرونة رائعة عندما يحصلون على الدعم المناسب."},{"sentence":"You need to be resilient to succeed in business.","translation":"تحتاج إلى المرونة للنجاح في الأعمال."}]',
ARRAY['tough','strong','adaptable','hardy','flexible'], ARRAY['fragile','vulnerable','brittle'], ARRAY['highly resilient','emotionally resilient','resilient economy'],
'{"ar":"مرن / قادر على التعافي","fr":"résilient","es":"resistente","de":"widerstandsfähig","zh":"有弹性的"}',
'RE-SILI-ENT: like a spring, you bounce back!'),

-- ===== TRAVEL & CULTURE =====
('destination', 'destination', 'noun', 'A2', 'travel', 'places', ARRAY['travel','geography','culture'], 'common', 'neutral',
'/ˌdestɪˈneɪʃən/', 'des-ti-NAY-shun', '/audio/destination.mp3',
'[{"sense":1,"definition":"The place to which someone or something is going or being sent"},{"sense":2,"definition":"A place that people travel to for its special qualities"}]',
'[{"sentence":"London is a popular tourist destination.","translation":"لندن وجهة سياحية شعبية."},{"sentence":"What''s your final destination?","translation":"ما هي وجهتك النهائية؟"}]',
ARRAY['location','place','goal','target'], ARRAY['origin','departure'], ARRAY['travel destination','dream destination','final destination','tourist destination'],
'{"ar":"وجهة","fr":"destination","es":"destino","de":"Ziel/Reiseziel","zh":"目的地"}',
'DEST-ination: where DESTINY takes you!'),

('heritage', 'heritage', 'noun', 'B2', 'culture', 'history', ARRAY['culture','history','travel','identity'], 'common', 'neutral',
'/ˈherɪtɪdʒ/', 'HER-i-tij', '/audio/heritage.mp3',
'[{"sense":1,"definition":"Property that is or may be inherited; inheritance"},{"sense":2,"definition":"Valued objects and qualities that have been passed down from previous generations"}]',
'[{"sentence":"The old city is a UNESCO World Heritage Site.","translation":"المدينة القديمة موقع تراث عالمي لليونسكو."},{"sentence":"Our cultural heritage defines who we are.","translation":"تراثنا الثقافي يحدد هويتنا."}]',
ARRAY['tradition','legacy','history','inheritance','culture'], ARRAY[], ARRAY['cultural heritage','world heritage','heritage site','national heritage'],
'{"ar":"تراث","fr":"patrimoine","es":"patrimonio","de":"Erbe","zh":"遗产"}',
'HERI-TAGE: HERIted from the past, TAGE-d for the future!'),

-- ===== TECHNOLOGY =====
('algorithm', 'algorithm', 'noun', 'B2', 'technology', 'computing', ARRAY['technology','computing','math','AI'], 'common', 'technical',
'/ˈælɡərɪðəm/', 'AL-guh-rith-um', '/audio/algorithm.mp3',
'[{"sense":1,"definition":"A process or set of rules to be followed in calculations or problem-solving, especially by a computer"}]',
'[{"sentence":"Search engines use complex algorithms to rank results.","translation":"تستخدم محركات البحث خوارزميات معقدة لترتيب النتائج."},{"sentence":"Learning to write algorithms is essential for programmers.","translation":"تعلم كتابة الخوارزميات أمر ضروري للمبرمجين."}]',
ARRAY['procedure','process','formula','method'], ARRAY[], ARRAY['machine learning algorithm','search algorithm','sorting algorithm'],
'{"ar":"خوارزمية","fr":"algorithme","es":"algoritmo","de":"Algorithmus","zh":"算法"}',
'Named after Persian mathematician Al-Khwarizmi!'),

('artificial intelligence', 'artificial-intelligence', 'noun', 'B2', 'technology', 'AI', ARRAY['technology','AI','computing','future'], 'common', 'technical',
'/ˌɑːrtɪˈfɪʃəl ɪnˈtelɪdʒəns/', 'ar-ti-FISH-ul in-TEL-i-jens', '/audio/artificial_intelligence.mp3',
'[{"sense":1,"definition":"The simulation of human intelligence processes by computer systems"},{"sense":2,"definition":"The ability of a computer to perform tasks that normally require human intelligence"}]',
'[{"sentence":"Artificial intelligence is transforming every industry.","translation":"الذكاء الاصطناعي يحول كل صناعة."},{"sentence":"AI can help you learn English more effectively.","translation":"يمكن للذكاء الاصطناعي مساعدتك على تعلم الإنجليزية بشكل أكثر فعالية."}]',
ARRAY['AI','machine intelligence','machine learning'], ARRAY['human intelligence'], ARRAY['artificial intelligence system','AI technology','AI-powered'],
'{"ar":"ذكاء اصطناعي","fr":"intelligence artificielle","es":"inteligencia artificial","de":"Künstliche Intelligenz","zh":"人工智能"}',
'AI = Artificial Intelligence = computerized thinking!'),

-- ===== ACADEMIC ENGLISH =====
('hypothesis', 'hypothesis', 'noun', 'C1', 'science', 'research', ARRAY['science','academic','research','thinking'], 'uncommon', 'formal',
'/haɪˈpɒθɪsɪs/', 'hy-POTH-uh-sis', '/audio/hypothesis.mp3',
'[{"sense":1,"definition":"A supposition or proposed explanation made on the basis of limited evidence as a starting point for further investigation"},{"sense":2,"definition":"A proposition made as a basis for reasoning"}]',
'[{"sentence":"The scientist developed a hypothesis and then tested it.","translation":"طور العالم فرضية ثم اختبرها."},{"sentence":"Learning vocabulary every day is my hypothesis for English success.","translation":"تعلم المفردات كل يوم هو فرضيتي للنجاح في الإنجليزية."}]',
ARRAY['theory','assumption','proposition','thesis','supposition'], ARRAY['conclusion','proof','fact'], ARRAY['test a hypothesis','research hypothesis','working hypothesis'],
'{"ar":"فرضية","fr":"hypothèse","es":"hipótesis","de":"Hypothese","zh":"假设"}',
'HYPO (under) + THESIS (placing) = placing an idea for testing!'),

('ambiguous', 'ambiguous', 'adjective', 'C1', 'language', 'meaning', ARRAY['language','communication','academic'], 'uncommon', 'formal',
'/æmˈbɪɡjuəs/', 'am-BIG-yoo-us', '/audio/ambiguous.mp3',
'[{"sense":1,"definition":"Open to more than one interpretation; having a double meaning"},{"sense":2,"definition":"Unclear or inexact because a choice between alternatives has not been made"}]',
'[{"sentence":"The instructions were ambiguous, so everyone interpreted them differently.","translation":"كانت التعليمات غامضة، لذا فسّرها الجميع بشكل مختلف."},{"sentence":"His smile was ambiguous - was he happy or being sarcastic?","translation":"كانت ابتسامته غامضة - هل كان سعيداً أم ساخراً؟"}]',
ARRAY['unclear','vague','uncertain','equivocal','obscure'], ARRAY['clear','unambiguous','definite','explicit'], ARRAY['deliberately ambiguous','morally ambiguous','ambiguous statement'],
'{"ar":"غامض / ذو معنيين","fr":"ambigu","es":"ambiguo","de":"mehrdeutig","zh":"模棱两可的"}',
'AMBI (both) + GUOUS: can go BOTH ways!'),

-- ===== MORE COMMON WORDS =====
('absolutely', 'absolutely', 'adverb', 'B1', 'emphasis', 'degree', ARRAY['emphasis','communication','expressions'], 'very_common', 'neutral',
'/ˈæbsəluːtli/', 'AB-suh-loot-lee', '/audio/absolutely.mp3',
'[{"sense":1,"definition":"With no qualification, restriction, or limitation; totally"},{"sense":2,"definition":"Used for emphasis or to express agreement strongly"}]',
'[{"sentence":"I absolutely love learning English!","translation":"أنا أحب تعلم اللغة الإنجليزية تماماً!"},{"sentence":"Are you sure? Absolutely!","translation":"هل أنت متأكد؟ بالتأكيد!"}]',
ARRAY['completely','totally','entirely','definitely','certainly'], ARRAY['partially','somewhat'], ARRAY['absolutely sure','absolutely not','absolutely right','absolutely love'],
'{"ar":"تماماً / بالتأكيد","fr":"absolument","es":"absolutamente","de":"absolut","zh":"绝对地"}',
'ABSOLUTE + LY = completely and totally!'),

('nevertheless', 'nevertheless', 'adverb', 'B2', 'contrast', 'linking', ARRAY['contrast','academic','writing'], 'common', 'formal',
'/ˌnevəðəˈles/', 'nev-er-thuh-LES', '/audio/nevertheless.mp3',
'[{"sense":1,"definition":"In spite of that; notwithstanding; all the same","usage_note":"Used to introduce a statement that contrasts with or seems to contradict something that has just been said"}]',
'[{"sentence":"The test was difficult. Nevertheless, she passed with flying colors.","translation":"كان الاختبار صعباً. ومع ذلك، نجحت بامتياز."},{"sentence":"He knew the risks. Nevertheless, he took the challenge.","translation":"عرف المخاطر. ومع ذلك، قبل التحدي."}]',
ARRAY['however','nonetheless','yet','still','even so'], ARRAY[], ARRAY['nevertheless important','nevertheless continue','and nevertheless'],
'{"ar":"مع ذلك / بالرغم من ذلك","fr":"néanmoins","es":"sin embargo","de":"nichtsdestotrotz","zh":"尽管如此"}',
'NEVER-THE-LESS: despite everything, still going!'),

('gradually', 'gradually', 'adverb', 'B1', 'change', 'pace', ARRAY['change','time','descriptions'], 'common', 'neutral',
'/ˈɡrædʒuəli/', 'GRAJ-oo-uh-lee', '/audio/gradually.mp3',
'[{"sense":1,"definition":"In a gradual way; slowly; by degrees"}]',
'[{"sentence":"Your English will improve gradually with daily practice.","translation":"ستتحسن لغتك الإنجليزية تدريجياً مع الممارسة اليومية."},{"sentence":"The temperature gradually increased throughout the day.","translation":"ارتفعت درجة الحرارة تدريجياً طوال اليوم."}]',
ARRAY['slowly','step by step','progressively','incrementally','little by little'], ARRAY['suddenly','abruptly','instantly'], ARRAY['gradually improve','gradually increase','gradually decrease'],
'{"ar":"تدريجياً","fr":"graduellement","es":"gradualmente","de":"allmählich","zh":"逐渐地"}',
'GRADE by GRADE, step by step = gradually!'),

('emphasize', 'emphasize', 'verb', 'B2', 'communication', 'language', ARRAY['communication','academic','language'], 'common', 'neutral',
'/ˈemfəsaɪz/', 'EM-fuh-syz', '/audio/emphasize.mp3',
'[{"sense":1,"definition":"To give special importance or prominence to something in speaking or writing"},{"sense":2,"definition":"To lay stress on a syllable or word when speaking"}]',
'[{"sentence":"I want to emphasize that daily practice is essential.","translation":"أريد التأكيد على أن الممارسة اليومية ضرورية."},{"sentence":"The teacher emphasized the importance of reading.","translation":"أكد المعلم على أهمية القراءة."}]',
ARRAY['stress','highlight','underline','accentuate','point out'], ARRAY['minimize','downplay'], ARRAY['emphasize the importance','emphasize the point','emphasize that'],
'{"ar":"يؤكد / يشدد","fr":"souligner","es":"enfatizar","de":"betonen","zh":"强调"}',
'EM-PHA-SIZE: make it big in size with emphasis!'),

('approximately', 'approximately', 'adverb', 'B1', 'numbers', 'estimation', ARRAY['numbers','math','academic','business'], 'common', 'neutral',
'/əˈprɒksɪmətli/', 'uh-PROK-si-mut-lee', '/audio/approximately.mp3',
'[{"sense":1,"definition":"Used to show that something is almost, but not completely, accurate or exact"}]',
'[{"sentence":"It takes approximately 3 months to reach B1 level with daily practice.","translation":"يستغرق الأمر حوالي 3 أشهر للوصول إلى مستوى B1 بممارسة يومية."},{"sentence":"The population of the city is approximately 5 million.","translation":"يبلغ عدد سكان المدينة حوالي 5 ملايين."}]',
ARRAY['about','around','roughly','nearly','circa'], ARRAY['exactly','precisely'], ARRAY['approximately equal','approximately correct','approximately how many'],
'{"ar":"تقريباً","fr":"approximativement","es":"aproximadamente","de":"ungefähr","zh":"大约"}',
'APPROX-imate-LY: getting CLOSE to the exact value!'),

('furthermore', 'furthermore', 'adverb', 'B2', 'writing', 'linking', ARRAY['writing','academic','communication'], 'common', 'formal',
'/ˈfɜːðərmɔːr/', 'FUR-ther-mor', '/audio/furthermore.mp3',
'[{"sense":1,"definition":"In addition; besides; moreover","usage_note":"Used to introduce a point that adds to or supports the previous point"}]',
'[{"sentence":"English is the global business language. Furthermore, it opens doors to international opportunities.","translation":"الإنجليزية هي لغة الأعمال العالمية. علاوة على ذلك، فإنها تفتح أبواباً للفرص الدولية."},{"sentence":"The app is fun. Furthermore, it is highly effective.","translation":"التطبيق ممتع. علاوة على ذلك، فهو فعال للغاية."}]',
ARRAY['moreover','additionally','also','in addition','besides'], ARRAY[], ARRAY['furthermore suggest','furthermore argue','and furthermore'],
'{"ar":"علاوة على ذلك","fr":"de plus","es":"además","de":"außerdem","zh":"此外"}',
'FURTHER + MORE = going even further, saying even more!');

-- Add a few more to reach 100 total (abbreviated for remaining slots)
INSERT INTO words (word, slug, part_of_speech, cefr_level, topic, subtopic, topics, frequency, register, phonetic_ipa, definitions, examples, synonyms, antonyms, translations, memory_tip) VALUES
('succeed', 'succeed', 'verb', 'B1', 'success', 'achievement', ARRAY['success','motivation'], 'very_common', 'neutral', '/səkˈsiːd/', '[{"sense":1,"definition":"To achieve the desired aim or result"}]', '[{"sentence":"If you practice every day, you will succeed.","translation":"إذا مارست كل يوم، ستنجح."}]', ARRAY['achieve','accomplish','triumph','prevail'], ARRAY['fail','lose'], '{"ar":"ينجح","fr":"réussir","es":"tener éxito","de":"erfolgreich sein","zh":"成功"}', 'SUC-CEED: CEED to success!'),
('motivate', 'motivate', 'verb', 'B1', 'psychology', 'drive', ARRAY['psychology','education','motivation'], 'common', 'neutral', '/ˈmoʊtɪveɪt/', '[{"sense":1,"definition":"To provide someone with a reason for doing something"}]', '[{"sentence":"What motivates you to learn English?","translation":"ما الذي يحفزك على تعلم الإنجليزية؟"}]', ARRAY['inspire','encourage','drive','stimulate'], ARRAY['discourage','demotivate'], '{"ar":"يحفز","fr":"motiver","es":"motivar","de":"motivieren","zh":"激励"}', 'MOTIVE + ATE: eat your motive for breakfast!'),
('vocabulary', 'vocabulary', 'noun', 'A2', 'language', 'words', ARRAY['language','learning','education'], 'very_common', 'neutral', '/vəˈkæbjʊleri/', '[{"sense":1,"definition":"The body of words used in a particular language or by a particular person"}]', '[{"sentence":"Building vocabulary is key to language learning.","translation":"بناء المفردات هو مفتاح تعلم اللغة."}]', ARRAY['words','lexicon','terminology','word bank'], ARRAY[], '{"ar":"مفردات","fr":"vocabulaire","es":"vocabulario","de":"Vokabular","zh":"词汇"}', 'VOCAB + ULARY: a library of your words!'),
('grammar', 'grammar', 'noun', 'A2', 'language', 'structure', ARRAY['language','learning','education'], 'very_common', 'neutral', '/ˈɡræmər/', '[{"sense":1,"definition":"The rules of a language governing the sounds, words, sentences, and other elements"}]', '[{"sentence":"Good grammar helps you communicate more clearly.","translation":"القواعد الجيدة تساعدك على التواصل بوضوح أكبر."}]', ARRAY['syntax','rules','structure'], ARRAY[], '{"ar":"قواعد اللغة","fr":"grammaire","es":"gramática","de":"Grammatik","zh":"语法"}', 'GRAM-MAR: GRAM of knowledge that goes far!'),
('pronunciation', 'pronunciation', 'noun', 'B1', 'language', 'phonetics', ARRAY['language','speaking','phonetics'], 'common', 'neutral', '/prəˌnʌnsiˈeɪʃən/', '[{"sense":1,"definition":"The way in which a word is pronounced"}]', '[{"sentence":"Good pronunciation makes you easier to understand.","translation":"النطق الجيد يجعلك أسهل فهماً."}]', ARRAY['diction','articulation','enunciation'], ARRAY[], '{"ar":"نطق","fr":"prononciation","es":"pronunciación","de":"Aussprache","zh":"发音"}', 'Pro-NOUNCE-iation: how you say your nouns!'),
('fluent', 'fluent', 'adjective', 'B1', 'language', 'ability', ARRAY['language','ability','goals'], 'common', 'neutral', '/ˈfluːənt/', '[{"sense":1,"definition":"Able to speak or write a language easily and accurately"}]', '[{"sentence":"She speaks fluent English after two years of study.","translation":"تتحدث الإنجليزية بطلاقة بعد سنتين من الدراسة."}]', ARRAY['proficient','articulate','skilled'], ARRAY['hesitant','broken'], '{"ar":"طليق","fr":"courant","es":"fluido","de":"fließend","zh":"流利的"}', 'FLUID + ENT: language flows like water!'),
('culture', 'culture', 'noun', 'A2', 'society', 'lifestyle', ARRAY['society','travel','arts','identity'], 'very_common', 'neutral', '/ˈkʌltʃər/', '[{"sense":1,"definition":"The ideas, customs, and social behaviour of a particular people or society"}]', '[{"sentence":"Learning a language means learning its culture too.","translation":"تعلم لغة يعني تعلم ثقافتها أيضاً."}]', ARRAY['civilization','society','tradition','heritage'], ARRAY[], '{"ar":"ثقافة","fr":"culture","es":"cultura","de":"Kultur","zh":"文化"}', 'CULT-URE: things people cultivate together!'),
('confidence', 'confidence', 'noun', 'B1', 'psychology', 'self', ARRAY['psychology','character','communication'], 'very_common', 'neutral', '/ˈkɒnfɪdəns/', '[{"sense":1,"definition":"The feeling or belief that one can rely on someone or something"}]', '[{"sentence":"Speaking practice builds your confidence in English.","translation":"ممارسة الكلام تبني ثقتك بالإنجليزية."}]', ARRAY['self-assurance','certainty','belief','assurance'], ARRAY['doubt','insecurity'], '{"ar":"ثقة","fr":"confiance","es":"confianza","de":"Zuversicht","zh":"信心"}', 'CON-FIDE-ENCE: having faith from within!'),
('patience', 'patience', 'noun', 'B1', 'character', 'virtue', ARRAY['character','psychology','learning'], 'common', 'neutral', '/ˈpeɪʃəns/', '[{"sense":1,"definition":"The capacity to accept delay, trouble, or suffering without becoming angry"}]', '[{"sentence":"Learning a language requires patience and consistency.","translation":"تعلم اللغة يتطلب صبراً وثباتاً."}]', ARRAY['tolerance','perseverance','endurance'], ARRAY['impatience','frustration'], '{"ar":"صبر","fr":"patience","es":"paciencia","de":"Geduld","zh":"耐心"}', 'PA-TIENT + CE: patients in hospital must wait patiently!'),
('practice', 'practice', 'noun', 'A2', 'learning', 'habit', ARRAY['learning','education','sports'], 'very_common', 'neutral', '/ˈpræktɪs/', '[{"sense":1,"definition":"Repeated exercise in or performance of an activity to acquire skill"},{"sense":2,"definition":"The actual application of a plan or method"}]', '[{"sentence":"Practice makes perfect!","translation":"الممارسة تصنع الكمال!"},{"sentence":"Daily practice is the secret to fluency.","translation":"الممارسة اليومية هي سر الطلاقة."}]', ARRAY['training','exercise','drill','rehearsal'], ARRAY['theory','neglect'], '{"ar":"ممارسة / تدريب","fr":"pratique","es":"práctica","de":"Übung","zh":"练习"}', 'PRACT-ICE: put your ICE (skills) into PRACTICE!'),
('inspire', 'inspire', 'verb', 'B1', 'motivation', 'emotion', ARRAY['motivation','arts','emotion'], 'common', 'neutral', '/ɪnˈspaɪər/', '[{"sense":1,"definition":"To fill someone with the urge or ability to do or feel something"},{"sense":2,"definition":"To breathe life into"}]', '[{"sentence":"Great teachers inspire their students to reach their potential.","translation":"المعلمون العظماء يلهمون طلابهم للوصول إلى إمكاناتهم."}]', ARRAY['motivate','encourage','stimulate','ignite'], ARRAY['discourage','dampen'], '{"ar":"يلهم","fr":"inspirer","es":"inspirar","de":"inspirieren","zh":"激励"}', 'IN-SPIRE: breathe IN the SPIRIT of greatness!'),
('diverse', 'diverse', 'adjective', 'B2', 'society', 'variety', ARRAY['society','culture','education','global'], 'common', 'formal', '/daɪˈvɜːrs/', '[{"sense":1,"definition":"Showing a great deal of variety; very different from each other"}]', '[{"sentence":"English connects diverse people from around the world.","translation":"الإنجليزية تربط الناس المتنوعين من جميع أنحاء العالم."}]', ARRAY['varied','assorted','different','heterogeneous'], ARRAY['uniform','homogeneous','same'], '{"ar":"متنوع","fr":"divers","es":"diverso","de":"vielfältig","zh":"多样的"}', 'Di-VERSE: many different VERSES in one song!'),
('innovate', 'innovate', 'verb', 'B2', 'business', 'creativity', ARRAY['business','technology','creativity'], 'common', 'formal', '/ˈɪnəveɪt/', '[{"sense":1,"definition":"To make changes in something established, especially by introducing new methods, ideas, or products"}]', '[{"sentence":"Successful companies continuously innovate.","translation":"الشركات الناجحة تبتكر باستمرار."}]', ARRAY['create','invent','pioneer','develop'], ARRAY['stagnate','copy'], '{"ar":"يبتكر","fr":"innover","es":"innovar","de":"innovieren","zh":"创新"}', 'INNOV-ATE: bring something NEW to the plate!'),
('sustainable', 'sustainable', 'adjective', 'B2', 'environment', 'development', ARRAY['environment','business','global_issues'], 'common', 'formal', '/səˈsteɪnəbəl/', '[{"sense":1,"definition":"Able to be maintained at a certain rate or level"},{"sense":2,"definition":"Conserving an ecological balance"}]', '[{"sentence":"We need sustainable solutions to climate change.","translation":"نحتاج إلى حلول مستدامة لتغير المناخ."}]', ARRAY['eco-friendly','renewable','green','viable'], ARRAY['unsustainable','wasteful'], '{"ar":"مستدام","fr":"durable","es":"sostenible","de":"nachhaltig","zh":"可持续的"}', 'SUSTAIN + ABLE: able to sustain itself!'),
('implement', 'implement', 'verb', 'B2', 'business', 'action', ARRAY['business','management','planning'], 'common', 'formal', '/ˈɪmplɪment/', '[{"sense":1,"definition":"To put a decision, plan, or agreement into effect"}]', '[{"sentence":"We will implement the new policy next month.","translation":"سننفذ السياسة الجديدة الشهر القادم."}]', ARRAY['execute','carry out','apply','enforce'], ARRAY['plan','propose'], '{"ar":"ينفذ / يطبق","fr":"mettre en œuvre","es":"implementar","de":"umsetzen","zh":"实施"}', 'IMPLE-MENT: using tools (implements) to get it done!'),
('collaborate', 'collaborate', 'verb', 'B2', 'teamwork', 'work', ARRAY['business','education','teamwork'], 'common', 'formal', '/kəˈlæbəreɪt/', '[{"sense":1,"definition":"To work jointly on an activity, especially to produce or create something"}]', '[{"sentence":"The two companies collaborated to create a new product.","translation":"تعاونت الشركتان لإنشاء منتج جديد."}]', ARRAY['cooperate','work together','partner','team up'], ARRAY['compete','work alone'], '{"ar":"يتعاون","fr":"collaborer","es":"colaborar","de":"zusammenarbeiten","zh":"协作"}', 'CO + LABOR + ATE: LABOR together CO-operatively!'),
('perceive', 'perceive', 'verb', 'C1', 'thinking', 'senses', ARRAY['thinking','psychology','philosophy'], 'common', 'formal', '/pərˈsiːv/', '[{"sense":1,"definition":"To become aware of through the senses"},{"sense":2,"definition":"To regard as being something"}]', '[{"sentence":"How do you perceive yourself as an English learner?","translation":"كيف تنظر إلى نفسك كمتعلم للغة الإنجليزية؟"}]', ARRAY['sense','detect','notice','observe'], ARRAY['ignore','miss'], '{"ar":"يدرك / يرى","fr":"percevoir","es":"percibir","de":"wahrnehmen","zh":"感知"}', 'PER-CEIVE: how you RECEIVE information through senses!'),
('inevitable', 'inevitable', 'adjective', 'C1', 'concepts', 'certainty', ARRAY['concepts','academic','philosophy'], 'common', 'formal', '/ɪnˈevɪtəbəl/', '[{"sense":1,"definition":"Certain to happen; unavoidable"}]', '[{"sentence":"Making mistakes is inevitable when learning a new language.","translation":"ارتكاب الأخطاء أمر حتمي عند تعلم لغة جديدة."}]', ARRAY['unavoidable','certain','inescapable','sure'], ARRAY['avoidable','preventable'], '{"ar":"حتمي","fr":"inévitable","es":"inevitable","de":"unvermeidlich","zh":"不可避免的"}', 'IN + EVITABLE: cannot be evaded!'),
('exemplify', 'exemplify', 'verb', 'C1', 'explanation', 'demonstration', ARRAY['academic','communication','teaching'], 'uncommon', 'formal', '/ɪɡˈzemplɪfaɪ/', '[{"sense":1,"definition":"To be a typical example of; to illustrate by example"}]', '[{"sentence":"This lesson exemplifies effective vocabulary teaching.","translation":"هذا الدرس يجسّد التدريس الفعّال للمفردات."}]', ARRAY['illustrate','demonstrate','represent','typify'], ARRAY[], '{"ar":"يجسّد / يمثّل","fr":"exemplifier","es":"ejemplificar","de":"veranschaulichen","zh":"举例说明"}', 'EXAMPLE + FY: to EX-AMP-LIFY with examples!'),
('magnificent', 'magnificent', 'adjective', 'B2', 'descriptions', 'praise', ARRAY['descriptions','arts','travel'], 'common', 'neutral', '/mæɡˈnɪfɪsənt/', '[{"sense":1,"definition":"Impressively beautiful, elaborate, or extravagant; splendid"}]', '[{"sentence":"The view from the top of the mountain was magnificent.","translation":"كان المنظر من قمة الجبل رائعاً."},{"sentence":"You''re doing a magnificent job with your English!","translation":"أنت تقوم بعمل رائع مع الإنجليزية!"}]', ARRAY['splendid','gorgeous','spectacular','glorious','superb'], ARRAY['awful','terrible','ugly'], '{"ar":"رائع / فخم","fr":"magnifique","es":"magnífico","de":"prachtvoll","zh":"壮丽的"}', 'MAGNI-FI-CENT: MAGNIFY it - it''s CENT-ered on greatness!');

COMMIT;
